### PR TITLE
Add boostrap to navbar for responsiveness

### PR DESCRIPTION
**Pull request by ogc1231**

### CODE REVIEW

**Comment by xiaoniuniu89** [comment]
This will conflict with most recent changes, you can rebase or merge with main:

git checkout main
git pull
git checkout your-branch-name
git rebase main 
(resolve any conflicts)
git push --force

**Review by xiaoniuniu89 — CHANGES_REQUESTED** [review]
pull latest and merge

**Comment by ogc1231** [comment]
Thanks, I'm not around for the 1.5 hours but ill do when i'm free. You go ahead and more stuff, I was only a simple add of a bootstrap navbar anyway

**Comment by xiaoniuniu89** [comment]
I can update for you , no worries

**Review by Renwar-P — COMMENTED** [review]
Converting navbar to Bootstrap.

**Pull request closed without merging**
