### PR TITLE
Add save state of settings

### PR DESCRIPTION
**Pull request by ogc1231**

### CODE REVIEW

**Review by Renwar-P — APPROVED** [review]

**Review by xiaoniuniu89 — COMMENTED** [review]
```
document.addEventListener('DOMContentLoaded', function() {
    // Save state of settings
localStorage.getItem('formData')

const formData1 = JSON.parse(localStorage.getItem('formData'));
const formData2 = JSON.parse(localStorage.getItem('formData'));

if (formData1.difficultyLevel) {
  document.querySelector(`input[name="inlineRadioOptions"][value="${formData1.difficultyLevel}"]`).checked = true;
}

if (formData2.questionType) {
  document.querySelector(`input[name="inlineRadioOptions2"][value="${formData2.questionType}"]`).checked = true;
}
});
```

**Comment by xiaoniuniu89** [comment]
can you try wrap this in an event listener, this way we can be sure the dom has loaded before checking local storage

**Review by xiaoniuniu89 — CHANGES_REQUESTED** [review]
see above and try

**Comment by xiaoniuniu89** [comment]
if it doesnt work, forget it

**Comment by ogc1231** [comment]
It seems to be saving the state on a hard refresh now Ctrl + Shift + r

**Comment by xiaoniuniu89** [comment]
> It seems to be saving the state on a hard refresh now Ctrl + Shift + r

local storage persists data by writing to users disk so it will always be whatever was last set , that would be expected behaviour persisting in local storage 

there is another type of storage called session storage that will only persist for the current session - we probably could have used that but since everything is already implemented in local storage, it seems acceptable for our use case for now

**Comment by ogc1231** [comment]
Okay cool, you happy for it to merged then?

**Review by xiaoniuniu89 — APPROVED** [review]

**Pull request merged**
